
if [ "$WORK_DIR" == "" ]; then
	WORK_DIR=/home/wrv/research/wasmperf
fi

WASM_COMPILER_DEFINES="-DWEBP_WASM_GENERIC_TREE -DWEBP_WASM_BITSIZE -DWEBP_WASM_DIRECT_FUNCTION_CALL -DWEBP_WASM_ALIAS_BITREADER -DWEBP_WASM_ALIAS_VP8PARSEINTRAMODEROW"

./build_wasm.sh
./build_wasmsimd.sh